#!/bin/bash

##  LaTeX2Ans: convert LaTeX as well as possible to the incompatible Ans-Delft version.
##  2020-05-06, Marc van der Sluys, HAN University of Applied Sciences, the Netherlands.

if [ ${#} -eq 0 ]
then
    command=`echo ${0} |sed -e 's/^.*\///g'`  # Remove path (e.g. ./)
    echo "This command converts LaTeX as well as possible to the incompatible Ans-Delft version."
    echo "Error: at least one argument was expected"
    echo "Syntax:  ${command} <LaTeX file> [<LaTeX file 2> <...>]"
    exit 1
fi

for LFILE in $@
do
    AFILE=`echo "$LFILE.ans" | sed 's|\.tex\.ans$|\.ans|'`
    echo "Converting $LFILE -> $AFILE"
    
    # Remove comment lines and label-only lines, remove remaining labels and \nonumbers, replace single $ with
    #   double $$ for inline math, remove \text..{}, replace \text{ with \mathrm{, remove \emph{, replace
    #   \dfrac -> \frac, replace ` -> ', remove eqnarray alignment & in many shapes, add space to EoL(?)
    sed \
	-e '/^ *%/d' \
	-e '/^ *\\label{[^}]*} *$/d' \
	-e 's|\\label{[^}]*}||g' \
	-e 's|\\nonumber||g' \
	-e 's|\$|$$|g' \
	-e 's|\\text..{|{|g' \
	-e 's|\\text{|\\mathrm{|g' \
	-e 's|\\emph{|{|g' \
	-e 's|\\dfrac{|\\frac{|g' \
	-e "s|\`|'|g" \
	-e 's| & *= *& | = |g' \
	-e 's| & *\\approx *& | \\approx |g' \
	-e 's| & *\\equiv *& | \\equiv |g' \
	-e 's| & *& | |g' \
	-e 's|&&| |g' \
	-e 's|&=&|=|g' \
	-e 's|$| |' \
	$LFILE > $AFILE
    
    # -e 's|\\begin{equation}|\\begin{eqnarray}|g' \  # Only works for hand-written exams!
    # -e 's|\\end{equation}|\\end{eqnarray}|g' \      # Only works for hand-written exams!
    
    
    # Multiline (-z) replace \begin/end{equation/eqnarray} with $$$ for display-mode math:
    sed -i -z \
	-e 's|\\begin{equation} *\n *|$$$|g' \
	-e 's|\n *\\end{equation} *\n|$$$\n|g' \
	-e 's|\\begin{eqnarray} *\n *|$$$|g' \
	-e 's|\n *\\end{eqnarray} *\n|$$$\n|g' \
	$AFILE
done


# Needed when not using a hand-written exam:

TFILE=".tempAnsfile.ans"

mv -f $AFILE $TFILE
sed \
    -e 's|~| |g' \
    -e 's|\\,| |g' \
    -e 's|\.\\ |\. |g' \
    $TFILE > $AFILE

rm -f $TFILE

