#!/bin/bash

##  LaTeX2Ans: convert LaTeX as well as possible to the incompatible Ans-Delft version.
##  2020-05-06, Marc van der Sluys, HAN University of Applied Sciences, the Netherlands.

if [ ${#} -eq 0 ]
then
    command=`echo ${0} |sed -e 's/^.*\///g'`  # Remove path (e.g. ./)
    echo "This command converts LaTeX as well as possible to the incompatible Ans-Delft version."
    echo "Error: at least one argument was expected"
    echo "Syntax:  ${command} <LaTeX file> [<LaTeX file 2> <...>]"
    exit 1
fi

for LFILE in $@
do
    AFILE=`echo "$LFILE.ans" | sed 's|\.tex\.ans$|\.ans|'`
    echo "Converting $LFILE -> $AFILE"
    
    sed \
	-e '/^ *%/d' \
	-e 's|\$|$$|g' \
	-e 's|\\begin{equation}|\\begin{eqnarray}|g' \
	-e 's|\\end{equation}|\\end{eqnarray}|g' \
	-e "s|\`|'|g" \
	-e 's|$| |'\
	$LFILE > $AFILE
done


